import "./globals.css";
import Header from "@/components/Header"
import FreeVbucks from "@/components/FreeVbucks";
import { verifySession } from "@/lib/session";
import Footer from "@/components/Footer";
import UsersAPI from "@/lib/api/Users";
import ShopAPI from "@/lib/api/Shop";



export const metadata = {
  title: "Fortnite Gamble Site",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await verifySession()
  let user;
  let allSkinsIds;
  if (session){
    user = await UsersAPI.read(session.user.id, session.accessToken)
    allSkinsIds = await ShopAPI.readAll()
  }
  return (
    <html lang="en">
      <body>
        <Header />
        {
          session ? (
            <FreeVbucks amount={100} user={user} allSkinsIds={allSkinsIds}/>
          ) : (
            <></>
          )
        }
        {children}
        <Footer className="footer"/>
      </body>
    </html>
  );
}
